#path to basespace files
input_data: "/data/gpfs/assoc/inbre/projects/melinda_yerka/GBS_progeny/input_gbs_dataset_forsnakemake"
ref: "/data/gpfs/assoc/inbre/projects/common_references/sbicolor_454_v3.0.1/Sbicolor_454_v3.0.1.fa"
